apiVersion: 1

datasources:
  - name: InfluxDB
    uid: P951FEA4DE68E13C5
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: true
    editable: true
    jsonData:
      version: InfluxQL
      httpMode: GET

  - name: Prometheus
    uid: PBFA97CFB590B2093
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
