spring.application.name=batch
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
server.port=8081

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none