logging:
  level:
    org.springframework.web.context.request.async: WARN
    org.apache.catalina.core.AsyncContextImpl: WARN

    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO

    org.hibernate.engine.transaction.internal: INFO
    org.springframework.transaction: INFO

    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: gymbarofit

spring:
<<<<<<< HEAD
  data:
    redis:
      repositories:
        enabled: false
  threads:
    virtual:
      enabled: true
=======
>>>>>>> origin/main
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  output.ansi.enabled: ALWAYS

app:
<<<<<<< HEAD
  ai:
    fastapi:
      base-url: ${FASTAPI_BASE_URL}
=======
>>>>>>> origin/main
  jwt:
    secretKey: ${JWT_SECRET}
    header:
      name: Authorization
      prefix: Bearer
    token:
      expireTime: 86400000 # 24시간 (ms)
    refresh-token:
      expireTime: 1209600000 # 14일 (ms)
      secure-cookie: true