spring:
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

app:
  upload:
    dir: /app/images
