spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      data-locations:
        - classpath:data-dev.sql
        - classpath:data-dev-sample.sql
        - classpath:data-k6-seed.sql
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

app:
  upload:
    dir: /app/images
